defmodule PhoenixEctoOpenApiDemoWeb.NotificationController do
  @moduledoc """
  Controller showing the full lifecycle of a polymorphic-embed backed
  resource through `ex_open_api_utils` + `OpenApiSpex`.

  Key points:

    * `NotificationRequest` / `NotificationResponse` are auto-generated by
      `use ExOpenApiUtils` on `PhoenixEctoOpenApiDemo.NotificationContext.Notification`.
    * The `:channel` property inside both is a `oneOf + discriminator` wrapper
      produced by `ExOpenApiUtils.Polymorphic.one_of/1`, so `OpenApiSpex.Plug.CastAndValidate`
      routes cast errors through the discriminator path (clean `:missing_field` /
      `:invalid_discriminator_value` / `:no_value_for_discriminator` errors
      instead of an unreadable `:one_of` wall).
    * `index/2` returns a list of notifications. The response schema is an
      `%OpenApiSpex.Schema{type: :array, items: NotificationResponse}` —
      each element carries its own `__type__` inside `channel`, so clients
      can pattern-match without another API call.
  """
  use PhoenixEctoOpenApiDemoWeb, :controller

  alias PhoenixEctoOpenApiDemo.NotificationContext
  alias PhoenixEctoOpenApiDemo.NotificationContext.Notification

  alias PhoenixEctoOpenApiDemo.OpenApiSchema.NotificationRequest
  alias PhoenixEctoOpenApiDemo.OpenApiSchema.NotificationResponse

  plug OpenApiSpex.Plug.CastAndValidate, json_render_error_v2: true

  action_fallback PhoenixEctoOpenApiDemoWeb.FallbackController

  tags(["Notification"])

  operation(:index,
    summary: "Lists notifications (with polymorphic channels)",
    operation_id: "Notification.list",
    responses: [
      ok:
        {"Notification list response", "application/json",
         %Schema{
           type: :array,
           description: "list of notifications — each channel is a oneOf variant",
           items: NotificationResponse
         }}
    ]
  )

  def index(conn, _params) do
    notifications = NotificationContext.list_notifications()
    render(conn, :index, notifications: notifications)
  end

  operation(:create,
    summary: "Creates a notification with a polymorphic channel",
    operation_id: "Notification.create",
    request_body: {"Notification creation body", "application/json", NotificationRequest},
    responses: [
      created: {"Notification response", "application/json", NotificationResponse}
    ]
  )

  # `body_params` is the cast'd request — but we pass the RAW params map
  # through to the changeset so `__type__` is preserved for
  # `cast_polymorphic_embed/3` to pick the right variant. OpenApiSpex already
  # validated the shape; at this point we just hydrate the Ecto struct.
  def create(conn, params) do
    with {:ok, %Notification{} = notification} <-
           NotificationContext.create_notification(params) do
      conn
      |> put_status(:created)
      |> put_resp_header("location", ~p"/api/notifications/#{notification}")
      |> render(:show, notification: notification)
    end
  end

  operation(:show,
    summary: "Fetches a notification",
    operation_id: "Notification.show",
    parameters: [
      id: [
        in: :path,
        description: "Notification ID",
        type: :string,
        example: "851b18d7-0c88-4095-9969-cbe385926420"
      ]
    ],
    responses: [
      ok: {"Notification response", "application/json", NotificationResponse}
    ]
  )

  def show(conn, %{id: id}) do
    notification = NotificationContext.get_notification!(id)
    render(conn, :show, notification: notification)
  end

  operation(:update,
    summary: "Updates a notification",
    operation_id: "Notification.update",
    parameters: [
      id: [
        in: :path,
        description: "Notification ID",
        type: :string,
        example: "851b18d7-0c88-4095-9969-cbe385926420"
      ]
    ],
    request_body: {"Notification update body", "application/json", NotificationRequest},
    responses: [
      ok: {"Notification response", "application/json", NotificationResponse}
    ]
  )

  def update(conn, %{id: id} = params) do
    notification = NotificationContext.get_notification!(id)

    with {:ok, %Notification{} = notification} <-
           NotificationContext.update_notification(notification, params) do
      render(conn, :show, notification: notification)
    end
  end

  operation(:delete,
    summary: "Deletes an existing notification",
    operation_id: "Notification.delete",
    parameters: [
      id: [
        in: :path,
        description: "Notification ID",
        type: :string,
        example: "851b18d7-0c88-4095-9969-cbe385926420"
      ]
    ],
    responses: [
      no_content: "Empty Response"
    ]
  )

  def delete(conn, %{id: id}) do
    notification = NotificationContext.get_notification!(id)

    with {:ok, %Notification{}} <- NotificationContext.delete_notification(notification) do
      send_resp(conn, :no_content, "")
    end
  end
end
